baseurl: /
languageCode: en-us
defaultContentLanguage: en
title: Bat Migration Europe
theme: syna
enableGitInfo: yes
version: 0.17.4
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
ignorefiles: content/dev/.*
googleAnalytics: ''
outputs:
  home:
    - HTML
    - JSON
frontmatter:
  date:
    - date
    - lastmod
  lastmod:
    - lastmod
    - :git
    - date
markup:
  goldmark:
    renderer:
      unsafe: yes
params:
  analytics:
    piwik: {}
  colors:
    danger: '#dc1200'
    dark: '#343a40'
    info: '#00c9dc'
    light: '#f8f9fa'
    primary: '#00838F'
    secondary: '#868e96'
    success: '#008f54'
    warning: '#fdf314'
  custom:
    favicon: logo2.ico
    favicon_ico_sizes: 16x16 32x32
    favicon_png: logo2.png
    favicon_svg: logo2.svg
  debug: yes
  description: European collaborative project to study bat migration
  fontawesome:
    disabled: no
    pro: no
  name: Bat Migration Europe
  style: {}
  unsafeEvents: yes
menu:
  copyright_footer:
    - name: About
      url: /about
      weight: 10
  footer:
    - name: French Museum of Natural History
      url: https://www.mnhn.fr/fr
      weight: 10
    - name: CESCO lab
      url: https://cesco.mnhn.fr/fr
      weight: 15
    - name: Bat research at the CESCO lab
      url: https://croemer3.wixsite.com/teamchiro
      weight: 20
#  footer_social:
    # - name: github
    #   pre: fab fa-github fa-stack-2x
    #   url: https://git.okkur.org/syna
    #   weight: 30
  main:
    - name: Home
      url: /
      weight: 10
    # - name: Fragments
    #   url: /fragments
    #   weight: 20
    - name: Project
      url: /project
      weight: 20
    - name: Partners
      url: /partners
      weight: 30
    - name: Newsletter
      url: /newsletter
      weight: 40
    - name: About
      url: /about
      weight: 50

